version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticvol:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - elk_net

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    ports:
      - 5601:5601
    restart: unless-stopped
    volumes:
      - kibanavol:/usr/share/kibana/data
    networks:
      - elk_net

  filebeat:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/beats/filebeat:7.5.0
    user: root
    container_name: filebeat
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    restart: unless-stopped
    volumes:
#      - logstashvol:/usr/share/logstash/data
      - filebeat_vol:/usr/share/filebeat/data
      - filebeat_log_vol:/usr/share/filebeat/logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk_net
volumes:
  elasticvol:
  kibanavol:
  filebeat_vol:
  filebeat_log_vol:

networks:
  elk_net:
    driver: bridge
