filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-elastic-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: kibana
        - equals:
            container.name: elasticsearch
        - equals:
            container.name: filebeat
    - index: "filebeat-postgres-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: postgres
    - index: "filebeat-redis-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: redis
    - index: "filebeat-sidekiq-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: sidekiq
    - index: "filebeat-nginx-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: nginx
    - index: "filebeat-drkiq-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.name: drkiq
    - index: "other-apps-%{[agent.version]}-%{+yyyy.MM.dd}"


logging.json: true
logging.metrics.enabled: false
